const Attachment = require("../models/Attachment");
const fs = require("fs");
const path = require("path");

/* =============================================================
   UPLOAD ATTACHMENT
   ============================================================= */
exports.uploadAttachment = async (req, res) => {
  try {
    const { taskId } = req.params;

    if (!req.file) {
      return res.status(400).json({ message: "No file uploaded" });
    }

    // ✅ FIXED: Storing originalname for UI and filename for the physical disk
    // This allows the frontend to show "image.png" instead of "17199933-image.png"
    const attachment = await Attachment.create({
      taskId,
      filename: req.file.originalname, // Original name from user
      storedName: req.file.filename,   // Unique name generated by multer
      fileUrl: `/uploads/${req.file.filename}`,
      uploadedBy: req.user?._id || "unknown", // Tracks the uploader ID if available
    });

    res.status(201).json(attachment);
  } catch (error) {
    console.error("Upload Error:", error.message);
    res.status(500).json({ message: error.message });
  }
};

/* =============================================================
   GET ATTACHMENTS BY TASK
   ============================================================= */
exports.getAttachmentsByTask = async (req, res) => {
  try {
    const { taskId } = req.params;
    
    // Fetching all attachments associated with the specific task
    const files = await Attachment.find({ taskId });
    
    res.json(files);
  } catch (error) {
    console.error("Fetch Error:", error.message);
    res.status(500).json({ message: error.message });
  }
};

/* =============================================================
   DELETE ATTACHMENT
   ============================================================= */
/**
 * ✅ FIXED: Deletes both the Database record and the physical file from /uploads
 */
exports.deleteAttachment = async (req, res) => {
  try {
    const { id } = req.params;

    // 1. Find the file record in MongoDB
    const file = await Attachment.findById(id);
    if (!file) {
      return res.status(404).json({ message: "Attachment not found" }); 
    }

 
    const filename = file.fileUrl.replace("/uploads/", "");
    const filePath = path.join(__dirname, "..", "uploads", filename);

    // 3. Delete from physical storage if the file actually exists on disk
    if (fs.existsSync(filePath)) {
      try {
        fs.unlinkSync(filePath);
      } catch (err) {
        console.warn(`File found but could not be deleted from disk: ${filePath}`);
      }
    }

    // 4. Delete the metadata record from MongoDB
    await file.deleteOne();

    res.json({ message: "Attachment deleted successfully" });
  } catch (err) {
    console.error("Delete Error:", err.message);
    res.status(500).json({ message: err.message });
  }
};